### ISSUE TITLE
Second call to StyleModule.mount with different shadow root has no effect

### ISSUE THREAD

**Issue by OttoLonnback** [marijnh/style-mod#12]
After the 4.1.1 update `StyleModule.mount` is broken when used on multiple shadow roots (with support for adoptedStyleSheets).

The function behaves correctly on the first call, but on the second call it does not apply any styles. This appears to be caused by the caching of `StyleSet`s in the `adoptedSet` variable. The `StyleSet` fetched from `adoptedSet` on the second call has its `root` property set to the root from the first call. When `StyleSet.mount` is called the old root is used and the new root receives no styles.

**Comment by marijnh** [comment]
Indeed, I introduced a bug there. Attached patch should help.

**Comment by OttoLonnback** [comment]
Thank you for the quick fix!
