### ISSUE TITLE
`"repository"` field missing from package.json

### ISSUE THREAD

**Issue by eemeli** [marijnh/style-mod#8]
Finding this repo is made a bit more complicated as e.g. https://www.npmjs.com/package/style-mod doesn't provide any links to here. This could be fixed by adding a `"repository"` field to package.json.

**Comment by marijnh** [comment]
Thanks for spotting that.

**Comment by wilsonpinto** [comment]
@marijnh any chance to publish a new version soon? 

We have an issue with our internal scanner that flags your great package as issue because no repository code is found.

Let me know if I can help in some way.

Thanks
